version: '3.4'

services:

  my-container:
    image: node:9
    volumes:
      - .:/usr/src/svc
    working_dir: /usr/src/svc
    ports:
      - 3000:3000
    command: bash -c "npm i && npm run dev"
    environment:
      - MONGO_URL=mongodb://mymongodb:27017/mydbname
    networks:
      - default

  mymongodb:
    image: mongo
    networks:
      - default